/home/salvacarrion/anaconda3/envs/nmt/bin/python /home/salvacarrion/Documents/Programming/Python/mltests/paper1/code/graphs/3_walk_eval_dirs.py
Local
scielo_health_biological_es_en: *********************************
	- health:
Generate test with beam=5: BLEU4 = 37.20, 65.4/42.6/30.5/22.5 (BP=1.000, ratio=1.032, syslen=149419, reflen=144751)
	- biological:
Generate test with beam=5: BLEU4 = 43.35, 69.3/48.7/37.0/28.9 (BP=0.995, ratio=0.995, syslen=144587, reflen=145377)
	- merged:
Generate test with beam=5: BLEU4 = 40.38, 67.3/45.6/33.7/25.7 (BP=1.000, ratio=1.013, syslen=294006, reflen=290128)
scielo_health_biological_pt_en: *********************************
	- health:
Generate test with beam=5: BLEU4 = 37.16, 66.8/42.9/30.2/22.0 (BP=1.000, ratio=1.008, syslen=113749, reflen=112799)
	- biological:
Generate test with beam=5: BLEU4 = 41.78, 68.7/47.0/35.3/27.4 (BP=0.994, ratio=0.994, syslen=127779, reflen=128542)
	- merged:
Generate test with beam=5: BLEU4 = 39.77, 67.8/45.1/32.9/24.9 (BP=1.000, ratio=1.001, syslen=241528, reflen=241341)

Process finished with exit code 0
